### PR TITLE
Erro de compilação quando  "Emit Runtime Type Information".

### PR DESCRIPTION
**Pull request by henriquewerlang**
Com a configuração abaixo, utilizando o XE 8, fazendo um "Build All" ocorre o erro " [dcc32 Error] Delphi.Mocks.pas(253): E2134 Type '<void>' has no type info ".
imagem
Para parar o erro coloquei a diretiva "{ $M- }", nas units que tem alguma declaração do tipo "out", e a variável não tiver tipo, para evitar esse erro.

### CODE REVIEW

**Comment by staticcat** [comment]
From Google Translate: "With the setting below , using the XE 8 , making a " Build All" is the error " [ Error dcc32 ] Delphi.Mocks.pas ( 253) : E2134 Type ' ' has no type info" .To stop the error put the policy " $ { M } " in the units that have some statement like " out" , and the variable has no type , to avoid this error."

**Comment by staticcat** [comment]
We are getting a different set of errors when turning on Emit Runtime Type Information. For example:

[dcc32 Error] Delphi.Mocks.pas(258): E2134 Type '<void>' has no type info
[dcc32 Fatal Error] Delphi.Mocks.pas(400): F2063 Could not compile used unit 'Delphi.Mocks.Utils.pas'

This is located on the function definition of:

function It(const AParamIndx : Integer) : ItRec;

I really don't want to have to turn off Type Information for the whole project just to allow the emitting of it. Is there another way around this issue?

**Comment by henriquewerlang** [comment]
Aqui acontece a mesma coisa, a diferença é que no lugar do '' aparece '<void>', se você der um duplo click no erro, vai na linha dessa função que você comentou. Mas esse erro de compilação, é por causa das funções que tem um parâmetro "out", como na linha 147, que tem a função "QueryImplementedInterface", que tem um parâmetro com out. Para resolver você pode colocar um tipo no parâmetro "out", ou desabilitar o "Run Time Type Operation", com a diretiva "{ $M- }", como eu mandei no pull request.

Anexei a imagem abaixo, com a implementação da classe que tem o parâmetro "out":
imagem

**Comment by staticcat** [comment]
Google English translation for my notes: "Here the same thing happens , the difference is that instead of ' ' appears '' if you double- click in the wrong, goes on line this function you said. But this compilation error , it is because of the functions that has a parameter "out " as in line 147, which has the function " QueryImplementedInterface " which has a parameter with out. To solve you can put a type parameter in the "out " or disable the "Run Time Type Operation " with the policy " $ { M } " as I sent the pull request .

I have attached the picture below , with the implementation of the class that has the parameter "out" :"

Doesn't seem to do that good a job. Please someone correct the above if it is not right.

**Comment by staticcat** [comment]
I don't understand how the un-typed out parameter is causing the compilation error when Emit Runtime Type Information is turned on for the project. Is the way Delphi-Mocks structured just not compatible with emitting runtime type information?

**Comment by fabriciocolombo** [comment]
Seems a bug. I found this on Quality Central: [E2134 Type '<void>' has no type info with typeless const parameter](http://qc.embarcadero.com/wc/qcmain.aspx?d=80828)
The workaround is disable type information using `{$M-}` around the class.

```delphi
 {$M-}
  IProxy = interface
    ['{C97DC7E8-BE99-46FE-8488-4B356DD4AE29}']
    function ProxyInterface : IInterface;
    function ProxyFromType(const ATypeInfo : PTypeInfo) : IProxy;
    procedure AddImplement(const AProxy : IProxy; const ATypeInfo : PTypeInfo);
    function QueryImplementedInterface(const IID: TGUID; out Obj): HRESULT; stdcall;
    procedure SetParentProxy(const AProxy : IProxy);
  end;
 {$M+}
```

**Comment by staticcat** [comment]
@henriquewerlang can you give the above a try and if it works submit a pr for this. Thanks.

**Comment by fabriciocolombo** [comment]
I updated my comment to follow the suggested workaround, otherwise the directive it will be always enabled. My mistake.

**Comment by staticcat** [comment]
Good pick up. Thanks for the updated comments.

**Comment by henriquewerlang** [comment]
Fiz a implementação com a sugestão do @fabriciocolombo.

**Comment by henriquewerlang** [comment]
Thanks. This pull request has been integrated manually.

**Pull request closed without merging**
